<?php
namespace Belsignum\PowermailVoucher\Domain\Repository;

/***
 *
 * This file is part of the "Voucher request with Powermail" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 *  (c) 2019 Andreas Sommer <sommer@belsignum.com>, Belsignum UG
 *
 ***/

/**
 * The repository for Campaigns
 */
class CampaignRepository extends \TYPO3\CMS\Extbase\Persistence\Repository
{

	/**
	 * @param int $uid
	 *
	 * @return object
	 */
	public function findByUid($uid)
	{
		$this->setIgnoreStoragePage();
		return parent::findByUid($uid);
	}

	/**
	 * @return array|\TYPO3\CMS\Extbase\Persistence\QueryResultInterface
	 */
	public function findAll()
	{
		$this->setIgnoreStoragePage();
		return parent::findAll(); // TODO: Change the autogenerated stub
	}

	/**
	 * ignore storage page
	 *
	 * @return void
	 */
	protected function setIgnoreStoragePage()
	{
		$querySettings = $this->createQuery()
							  ->getQuerySettings()
							  ->setRespectStoragePage(FALSE);
		$this->setDefaultQuerySettings($querySettings);
	}
}
